# Generated by Django 2.2.4 on 2020-09-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200926_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='productId',
        ),
    ]
