# Generated by Django 2.2.4 on 2020-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20201002_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
